Repository wecode-bootcamp-korea/19-1st-KLUSH-frontend, pull requests merged in 2021-04, with the labels that each got.

#1 [19기 정새미] Modify:common.scss 수정
  src/Styles/common.scss
Labels: Status: 도움 요청

#3 [19기 김희열] Add: 리팩토링 및 이미지 캐러셀 구현 중
  package-lock.json
  package.json
  public/data/navdata.json
  public/data/recommendList.json
  public/index.html
  src/Components/Footer/Footer.js
  src/Components/Footer/Footer.scss
  src/Components/Nav/CategoryIntroduce/CategoryIntroduce.js
  src/Components/Nav/CategoryIntroduce/CategoryIntroduce.scss
  src/Components/Nav/CategoryProducts/CategoryProducts.js
  src/Components/Nav/CategoryProducts/CategoryProducts.scss
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Pages/Main/Component/ArticleList/ArticleList.js
  src/Pages/Main/Component/ArticleList/ArticleList.scss
  src/Pages/Main/Component/MainAll/MainAll.js
  src/Pages/Main/Component/MainAll/MainAll.scss
  src/Pages/Main/Component/MainAll/MainSectionEvent/MainSectionEvent.js
  src/Pages/Main/Component/MainAll/MainSectionEvent/MainSectionEvent.scss
  src/Pages/Main/Component/MainAll/MainSectionRecommend/MainSectionRecommend.js
  src/Pages/Main/Component/MainAll/MainSectionRecommend/MainSectionRecommend.scss
  src/Pages/Main/Component/MainAll/MainSectionSpa/MainSectionSpa.js
  src/Pages/Main/Component/MainAll/MainSectionSpa/MainSectionSpa.scss
  src/Pages/Main/Main.js
  src/Pages/Main/Main.scss
  src/Styles/common.scss
  src/Styles/reset.scss
  src/index.js
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#2 [19기 정새미] 상품페이지 레이아웃 구현 완료 Feature/product list
  .prettierrc
  package-lock.json
  public/data/productListData.json
  src/Pages/ProductDetail/ProductDetail.js
  src/Pages/ProductList/Component/PrdLists.js
  src/Pages/ProductList/Component/PrdLists.scss
  src/Pages/ProductList/ProductList.js
  src/Pages/ProductList/ProductList.scss
  src/Styles/variable.scss
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#9 [19기 정새미] 상품 페이지 라벨링 기능 구현 완료 리뷰요청 Feature/product list
  public/data/productListData.json
  src/Pages/ProductList/Component/PrdLists.js
  src/Pages/ProductList/Component/PrdLists.scss
  src/Pages/ProductList/ProductList.js
  src/config.js
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#4 [19기 김태현] 회원가입 페이지 기능 수정 완료
  src/Pages/SignUp/Components/SignUpList/SignUpList.js
  src/Pages/SignUp/SignUp.js
  src/Pages/SignUp/SignUp.scss
Labels: Status: 리뷰 요청

#5 [19기 김태현] 로그인 페이지 기능 수정 완료
  public/index.html
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
  src/config.js
Labels: Status: 리뷰 요청

#10 [19기 김희열] Modified: feature/main 내 cart 파일 삭제 및 feature/cart로 이동
  public/data/navdata.json
  public/data/recommendList.json
  src/Components/Footer/Footer.js
  src/Components/Nav/CategoryProducts/CategoryProducts.js
  src/Components/Nav/CategoryProducts/CategoryProducts.scss
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Pages/Main/Component/ArticleList/ArticleList.js
  src/Pages/Main/Component/ArticleList/ArticleList.scss
  src/Pages/Main/Component/MainAll/MainSectionEvent/MainSectionEvent.js
  src/Pages/Main/Component/MainAll/MainSectionEvent/MainSectionEvent.scss
  src/Pages/Main/Component/MainAll/MainSectionRecommend/MainSectionRecommend.js
  src/Pages/Main/Component/MainAll/MainSectionRecommend/MainSectionRecommend.scss
  src/Pages/Main/Component/MainAll/MainSectionSpa/MainSectionSpa.js
  src/Pages/Main/Main.scss
  src/Styles/common.scss
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#6 [19기 정새미] 상품 디테일 페이지 리뷰 수정 완료
  public/data/productListData.json
  public/datas/productData.json
  public/datas/productList.json
  src/Pages/Main/Component/MainAll/MainSectionRecommend/MainSectionRecommend.js
  src/Pages/ProductDetail/Component/Comments/Comment.js
  src/Pages/ProductDetail/Component/ProductInfo/ProductInfo.js
  src/Pages/ProductDetail/Component/ProductInfo/ProductInfo.scss
  src/Pages/ProductDetail/Component/ProductWeight/ProductWeight.js
  src/Pages/ProductDetail/Component/ProductWeight/ProductWeight.scss
  src/Pages/ProductDetail/Component/Refund/Refund.js
  src/Pages/ProductDetail/Component/Refund/Refund.scss
  src/Pages/ProductDetail/Component/ScoreReview/ScoreReview.js
  src/Pages/ProductDetail/Component/ScoreReview/ScoreReview.scss
  src/Pages/ProductDetail/Goods/Goods.js
  src/Pages/ProductDetail/Goods/Goods.scss
  src/Pages/ProductDetail/ProductDetail.js
  src/Pages/ProductDetail/ProductDetail.scss
  src/Pages/ProductList/Component/Card.js
  src/Pages/ProductList/Component/Cards.scss
  src/Pages/ProductList/ProductList.js
  src/Pages/ProductList/ProductList.scss
  src/Routes.js
  src/Styles/variable.scss
  src/config.js
Labels: Status: Conflict 발생

#12 [19기 김태현] 로그인 페이지 기능 수정 완료
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
  src/Pages/SignUp/SignUp.js
Labels: Status: 리뷰 요청

#13 [19 김태현] 회원가입 페이지 기능 수정 완료
  src/Pages/SignUp/SignUp.js
  src/config.js
Labels: Status: Conflict 발생

#11 [19기 김희열] Add: 총 금액 로직 완료, fetch 수정 완료
  public/data/cartList.json
  src/Components/Footer/Footer.js
  src/Components/Footer/Footer.scss
  src/Components/Nav/CategoryProducts/CategoryProducts.scss
  src/Components/Nav/Nav.js
  src/Pages/Cart/Cart.js
  src/Pages/Cart/Cart.scss
  src/Pages/Main/Component/MainAll/MainSectionRecommend/MainSectionRecommend.js
  src/Styles/common.scss
  src/config.js
Labels: Status: 리뷰 요청

#14 [19기 김희열] Add: 충돌 해결 완료
  src/Components/Nav/CategoryProducts/CategoryProducts.js
  src/Components/Nav/Nav.js
Labels: Status: 리뷰 요청

#8 [19기 김태현] 댓글 컴포넌트 기능 수정
  src/Components/Nav/Nav.js
  src/Pages/ProductDetail/Components/Comments/Comment.js
  src/Pages/ProductDetail/Components/Comments/Member/Member.js
  src/Pages/ProductDetail/Components/Comments/Member/Member.scss
  src/Pages/ProductDetail/ProductDetail.js
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청
